### ISSUE TITLE
Monitor connection issue.

### ISSUE THREAD

**Issue by deprale** [JKSunny/EternalJK#6]
Reporting a bug? Please make sure you've given the following information in detail - thanks!

**Operating system and version:**
Win10 22H2

**Description of the bug (and if possible, steps to reproduce the bug):**
Was playing game, my power cable disconnected from main monitor (I have 2), game went to second monitor, I reconnected the main monitor the game was being played on and now the game is forever "invisible" or the wrong size (maybe 1x1?), I can hear and interact with the game but all I see is my windows desktop.

**What did you expect to happen instead?**
To see the game.

**Comment by JKSunny** [comment]
Hey Deprale,

I tried reproducing your case, even by disconnecting the monitors datacable while ingame.
In my case, the game stayed on the second monitor. 
Able to move it back to primary screen by pressing <kbd>⊞ Windows</kbd> + <kbd>⇧ Shift</kbd> + ( <kbd>← Left</kbd> or <kbd>→ Right</kbd> ) 

After a restart, the game however launched on primary monitor as usual.

I suspect this behaivior is gpu and driver dependent, and is a guessing game.

In your case, the game might have written incorrect settings to your config file.

You can try replacing "GameData/EternalJk/eternaljk.cfg" with a fresh copy in the [latest release](https://github.com/JKSunny/EternalJK/releases/tag/latest)
\****Please be sure to backup your current "eternaljk.cfg"!!***\*

If this resolves the issue, you can compare the two files using something like [Diffchecker](https://www.diffchecker.com/)

Hope this is of any help.
